apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-deployment
  namespace: ivolve
  labels:
    app: cloud-devops-app
    framework: flask
    language: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-devops-app
  template:
    metadata:
      labels:
        app: cloud-devops-app
    spec:
      containers:
        - name: cloud-devops-container
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          image: redaeid/ivolvefinalproject:74
          ports:
            - containerPort: 5000
        
