apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-deployment2
  namespace: ivolve
  labels:
    app: cloud-devops-app2
    framework: flask
    language: python
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cloud-devops-app2
  template:
    metadata:
      labels:
        app: cloud-devops-app2
    spec:
      containers:
        - name: cloud-devops-container
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          image: redaeid/ivolvefinalproject:78
          ports:
            - containerPort: 5000
        
