apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-deployment
  namespace: ivolve
  labels:
    app: cloud-devops-app
    framework: flask
    language: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-devops-app
  template:
    metadata:
      labels:
        app: cloud-devops-app
    spec:
      containers:
        - name: cloud-devops-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          image: redaeid/ivolvefinalproject:78
          ports:
            - containerPort: 5000
        
